version: '3.7'

services:
  client-grade:
    build: .
    image: client-grade:latest
    hostname: client-grade
    ports:
      - "9090:9090"
    expose:
      - "9090:9090"
    environment:
      BPMN_LOCATION: /app/bpmn/ElfinTest.bpmn
      GATE_WAY_ADDRESS: zeebe
      GATE_WAY_PORT: 26500
      ELASTIC_SEARCH_HOST: elasticsearch
      ELASTIC_SEARCH_PORT: 9200
    networks:
      - camunda_camunda-platform

networks:
  camunda_camunda-platform:
    external: true