spring:
  application:
    name: Elfin

server:
  port: 9090

bpmn:
  location: ${BPMN_LOCATION:src/main/resources/bpmn/ElfinTest.bpmn}

dmn:
  location: ${DMN_LOCATION:src/main/resources/dmn/GradeClient.dmn}

elasticsearch-connection:
  host: ${ELASTIC_SEARCH_HOST:localhost}
  port:  ${ELASTIC_SEARCH_PORT:9200}